server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VictoriaMRamirez/PracticaIntegradorBack
          default-label: master
          force-pull: true
          search-paths: configData
