server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-student
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/digitalhousedev #jdbc:mysql://localhost:3306/digitalhouse-dev
    username: root #usr-digitalhouse
    password: 29031999 #pwd-digitalhouse
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: false
      serviceURL:
         defaultZone: http://localhost:8761/eureka